
export interface MicroscopeDataPoint {
  m: number;
  wd: number;
  fovX: number;
  fovY: number;
  dof: number;
}

export const MICROSCOPE_DATA: MicroscopeDataPoint[] = [
  { m: 10, wd: 142.6, fovX: 60.69, fovY: 34.14, dof: 26.01 },
  { m: 20, wd: 60.1, fovX: 30.35, fovY: 17.07, dof: 7.01 },
  { m: 30, wd: 33.6, fovX: 20.23, fovY: 11.38, dof: 3.34 },
  { m: 40, wd: 21.0, fovX: 15.17, fovY: 8.53, dof: 2.01 },
  { m: 50, wd: 14.0, fovX: 12.14, fovY: 6.83, dof: 1.37 },
  { m: 60, wd: 9.8, fovX: 10.11, fovY: 5.69, dof: 1.01 },
  { m: 70, wd: 7.3, fovX: 8.67, fovY: 4.88, dof: 0.78 },
  { m: 80, wd: 5.7, fovX: 7.59, fovY: 4.27, dof: 0.63 },
  { m: 90, wd: 4.8, fovX: 6.74, fovY: 3.79, dof: 0.52 },
  { m: 100, wd: 4.3, fovX: 6.07, fovY: 3.41, dof: 0.44 },
  { m: 110, wd: 4.2, fovX: 5.52, fovY: 3.10, dof: 0.38 },
  { m: 120, wd: 4.3, fovX: 5.06, fovY: 2.85, dof: 0.34 },
  { m: 130, wd: 4.7, fovX: 4.67, fovY: 2.63, dof: 0.31 },
  { m: 140, wd: 5.2, fovX: 4.34, fovY: 2.44, dof: 0.28 },
  { m: 150, wd: 5.8, fovX: 4.05, fovY: 2.28, dof: 0.26 },
  { m: 160, wd: 6.5, fovX: 3.79, fovY: 2.13, dof: 0.24 },
  { m: 170, wd: 7.3, fovX: 3.57, fovY: 2.01, dof: 0.22 },
  { m: 180, wd: 8.1, fovX: 3.37, fovY: 1.90, dof: 0.20 },
  { m: 190, wd: 9.1, fovX: 3.20, fovY: 1.80, dof: 0.19 },
  { m: 200, wd: 10.0, fovX: 3.03, fovY: 1.71, dof: 0.18 },
  { m: 210, wd: 11.0, fovX: 2.89, fovY: 1.63, dof: 0.17 },
  { m: 220, wd: 12.1, fovX: 2.76, fovY: 1.55, dof: 0.16 }
];

export const INCH_TO_MM = 25.4;

export const GCODE_HEADER = [
  "; Generated by MicroScan G-Code Architect",
  "G21 ; Units in mm",
  "G90 ; Absolute positioning",
  "M82 ; Extruder to absolute mode",
  "; --- User Defined Origin ---",
  "G92 X0 Y0 Z10 ; Set current position as 0,0 with Z at safety height",
  "G1 Z10 F600 ; Ensure we are at safety height",
  "; --- Start Scanning Sequence ---"
];

export const GCODE_FOOTER = [
  "; --- End Scanning Sequence ---",
  "G1 Z30 F1200 ; Lift head away from sample",
  "G1 X0 Y0 F3000 ; Return to the starting point",
  "M84 ; Disable motors (optional, allows manual movement)",
  "M117 Scan Complete"
];
